### ISSUE TITLE
Class auth.context does not exist

### ISSUE THREAD

**Issue by belapie** [Propaganistas/Laravel-Auth-Context#1]
Hi,

I follow the procedure like you explained.

* Added "propaganistas/laravel-auth-context": "^1.0" to my composer.json
* composer update
* Added "Propaganistas\LaravelAuthContext\AuthContextServiceProvider::class" to config/app.php
* Created a class name "App\Http\Context\AdminContext" (copy/past from your).
* In AppServiceProvider.php, in the register() i add : 

> public function register()
> {
> 	Propaganistas\LaravelAuthContext\Facades\AuthContext::register(App\Http\Context\AdminContext::class);
> }

* But ends up with an error : 

> ReflectionException in Container.php line 737: 
> Class auth.context does not exist

I added the full namespaces so it's more clear of what i use.

Thanks

**Comment by belapie** [comment]
Ok i found out.. You have to place "Propaganistas\LaravelAuthContext\AuthContextServiceProvider::class" BEFORE "AppServiceProvider".

Please fix that in the documentation.

Regards

**Comment by Propaganistas** [comment]
The error you encountered is completely self-caused. You attempt to register an AuthContext in `AppServiceProvider`, so in that case it is quite obvious that this package has to be loaded before `AppServiceProvider`.

You are completely free on where to register any AuthContexts, it is not limited to `AppServiceProvider`.
