### ISSUE TITLE
php artisan migrate issue

### ISSUE THREAD

**Issue by PhilipGil** [Propaganistas/Laravel-Auth-Context#2]
So looking for laravel 5.2 multi-auth example. So stoked I found your example on github. Just having problems with initial migrate. Total newbie.

What I have done: homestead works well, been building small apps from homestead to tryout laravel. Migrations, db:seed etc works 100%. No problem.

Also tried out other laravel starters from github - all work well.

Just this one after trying to migrate generates the below warnings. As I've said, Newbie, could be just a small thing I'm not seeing. SOS anyone. Thanks!

vagrant@homestead:~/Code/easy1$ php artisan migrate
PHP Warning:  require(/home/vagrant/Code/easy1/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/vagrant/Code/easy1/bootstrap/autoload.php on line 17
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Code/easy1/artisan:0
PHP   2. require() /home/vagrant/Code/easy1/artisan:16

Warning: require(/home/vagrant/Code/easy1/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/vagrant/Code/easy1/bootstrap/autoload.php on line 17

Call Stack:
    0.0004     226032   1. {main}() /home/vagrant/Code/easy1/artisan:0
    0.0020     228648   2. require('/home/vagrant/Code/easy1/bootstrap/autoload.php') /home/vagrant/Code/easy1/artisan:16

PHP Fatal error:  require(): Failed opening required '/home/vagrant/Code/easy1/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/vagrant/Code/easy1/bootstrap/autoload.php on line 17
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Code/easy1/artisan:0
PHP   2. require() /home/vagrant/Code/easy1/artisan:16

Fatal error: require(): Failed opening required '/home/vagrant/Code/easy1/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/vagrant/Code/easy1/bootstrap/autoload.php on line 17

Call Stack:
    0.0004     226032   1. {main}() /home/vagrant/Code/easy1/artisan:0
    0.0020     228648   2. require('/home/vagrant/Code/easy1/bootstrap/autoload.php') /home/vagrant/Code/easy1/artisan:16

**Comment by Propaganistas** [comment]
This is unrelated to the package. Your composer autoload file simply doesn't exist. Run `composer install && composer dump-autoload` to fix this.

Additionally, you shouldn't use this package. Starting from version 5.2 Laravel has built-in support for multi-auth. Check [this blog post](https://mattstauffer.co/blog/multiple-authentication-guard-drivers-including-api-in-laravel-5-2) for some information
